In [17]:
import numpy as np

In [18]:
perc_gel = np.array([20,15,10])

In [19]:
# volume of gelation solution per experiment in microliters
conc_igacure = 2500 # microgramms per mil
vol = 100 # microliters
per_igacure = 0.05
vol_igacure = vol*per_igacure/100*1000/2.5 # in microliters
print(vol_igacure)

20.0


In [20]:
# gel solutions - we are starting with 30% gelatin
vol_gelatin = vol*perc_gel/30
vol_cells = vol-vol_gelatin-vol_igacure
print(vol_gelatin, vol_cells)

[ 66.66666667  50.          33.33333333] [ 13.33333333  30.          46.66666667]


In [21]:
# cells: we want 10 million cells per ml
cells_per_ml = 10e6
cells_per_sample = vol /1000 *cells_per_ml
print(cells_per_sample)
cell_stock_volume = vol_cells[0]*cells_per_ml/cells_per_sample
print(cell_stock_volume)

1000000.0
133.333333333


In [22]:
# now we calculate the extra growth media that have to be added
vol_extra_media = vol - vol_gelatin - vol_igacure - vol_cells[0]

In [25]:
print(vol_gelatin)
print(vol_igacure*np.ones(3))
print(vol_cells[0]*np.ones(3))
print(vol_extra_media)

[ 66.66666667  50.          33.33333333]
[ 20.  20.  20.]
[ 13.33333333  13.33333333  13.33333333]
[  0.          16.66666667  33.33333333]
